### ISSUE TITLE
How to ssh onto 172.17.0.2

### ISSUE THREAD

**Issue by stanleyxu2005** [gustavonalle/docker#2]
I've launched your YARN cluster successfully. I'd like to copy some files to the HDFS. But I cannot log on the machine via SSH. The server asks me about the root password. I tried no password and also tried "root", "123456", "docker". None of them works. What is the root password actually? Any hint is appreciated.

**Comment by gustavonalle** [comment]
Hi, the container maps the folder where it is launched internally to
'/usr/local/sample/'.
You can also use 'docker exec' to gain shell access to the container:

docker exec -ti master bash

Gustavo

**Comment by stanleyxu2005** [comment]
Thanks a lot
